### ISSUE TITLE
Web基礎 前期期末課題 講評

### ISSUE THREAD

**Issue by wangchangdog** [ibuki1204/about-me#1]
## Good: 

AIをフルに使って実装を簡易化されていました。

## More:  

ページの画像コンテンツやCSSのリンクなどの参照切れが多く発生しているようです。非常に残念です。

**Comment by ibuki1204** [comment]
僕が提出日の授業で制作してた時、写真は絶対に参照切れしていなかったです。今日確認してみても参照切れになっていなかったので何かの間違いだと思います。cssは多少参照切れはあるとは思うのですが、それでもちゃんとしたデザインになっているはずです。採点されてからで申し訳ないのですが、もう一度見てもらうことは可能でしょうか。提出日を最後にそこから1度もaboutmeの修正はしていません。
